#!/home/colinchan/talk/env/bin/python3
import inspect

from slides import bash, display_slides, flair, format_slide, slide, wait


@slide
def colortest():
    """Testing code highlighting

    ```bash
    #!/bin/bash
    set -o pipefail
    if [[ "$foo" == bar ]]; then
      exec sleep 5
    fi
    ```

    ```python3
    from itertools import chain
    print(f"{foo}\\n is {bar}")
    @foo
    def bar(a: int = None, b: bool = False) -> Optional[int]:
        raise ValueError()
    ```
    """


@slide
def readline_slide():
    """Readline

    Readline provides fancy line-editing on Linux.

    * tab completion
    * history

    ```python3
    import readline, rlcompleter
    readline.parse_and_bind("tab: complete")
    ```
    """
    print(format_slide("`input()` **without** readline:").rstrip("\n"))
    try:
        input(">>> ")
    except (EOFError, KeyboardInterrupt):
        print()
    import readline
    import rlcompleter
    readline.parse_and_bind("tab: complete")
    print(format_slide("`input()` **with** readline:").rstrip("\n"))
    try:
        input(">>> ")
    except (EOFError, KeyboardInterrupt):
        print()


@slide
def pythonstartup():
    """Customized interactive interpreter

    By setting `PYTHONSTARTUP`, you can initialize your interactive
    sessions.

    * Import things you use frequently
    * Enable readline

    ```python3
    from random import choice, sample
    from shlex import quote
    parser = argparse.ArgumentParser()
    ```

    ```python3
    ```
    """
    bash()


@slide
def slides_slide():
    """Slides in the terminal

    I made a slide renderer in Python (for this talk).

    * Slides are **functions** with content in the docstring
    * Then you can run *arbitrary code*!
    """
    code = inspect.getsource(slides_slide)
    print(format_slide(f"```python3\n{code}\n```"), end="")


@slide
def slides_issues():
    """Slides in the terminal

    Incomplete list of things that don’t work yet:

    ## Formatting
    * nested lists (actually nested *anything*)
    * blockquotes
    * tables

    ## Functionality
    * go to previous slide
    * jump to a specific slide
    * resizing the window during the presentation
    """


with flair():
    display_slides()
