#!/home/colinchan/talk/env/bin/python3
import inspect

from slides import (
    bash,
    display_slides,
    flair,
    format_slide,
    ipython,
    python,
    slide,
    wait,
)


@slide
def title():
    """Using Python for Efficiency (and Fun!)"""
    bash(
        history=["pwd", "whoami"],
        extrarc=['pwd() { (( $# == 0 )) && echo /facebook || command pwd "$@"; }'],
    )


@slide
def readline_slide():
    """Readline

    Readline provides fancy line-editing on Linux.

    * tab completion
    * history
    * editing shortcuts

    ```python3
    import readline, rlcompleter
    readline.parse_and_bind("tab: complete")
    ```
    """
    print(format_slide("Prompt **without** readline:").rstrip("\n"))
    try:
        input(">>> ")
    except (EOFError, KeyboardInterrupt):
        print()
        pass

    import readline
    import rlcompleter

    readline.parse_and_bind("set show-mode-in-prompt off")
    readline.parse_and_bind("tab: complete")
    print(format_slide("Prompt **with** readline:").rstrip("\n"))
    python()


@slide
def readline_inputrc():
    """Readline

    Readline can be configured in `~/.inputrc`.

    ```bash
    set blink-matching-paren on
    set colored-completion-prefix on
    set completion-ignore-case on
    set completion-map-case on
    set enable-bracketed-paste on
    ```
    """
    python()
    ipython()


@slide
def pythonstartup():
    """Customized interactive interpreter

    By setting `PYTHONSTARTUP`, you can initialize your interactive
    sessions.

    * Import things you use frequently
    * ~~Enable readline~~

    ```python3
    from datetime import date, datetime, timedelta
    from random import choice, sample
    parser = argparse.ArgumentParser()
    ```
    """
    bash(history=["e ~/.pythonrc", "printenv PYTHONSTARTUP"])


@slide
def slides_demo():
    """Slides in the terminal

    I made a slide renderer in Python (for this talk).

    * Slides are **functions** with content in the docstring
    * Then you can run *arbitrary code*!
    """
    code = inspect.getsource(slides_demo)
    print(format_slide(f"```python3\n{code}\n```"), end="")


@slide
def slides_known_issues():
    """Slides in the terminal

    Incomplete list of things that don’t work yet:

    ## Formatting
    * nested lists (actually nested *anything*)
    * blockquotes
    * tables

    ## Functionality
    * go to previous slide
    * jump to a specific slide
    * resizing the window during the presentation
    """


with flair():
    display_slides()
