#!/home/colinchan/talk/env/bin/python3
import inspect
import os
import pty
import sys
import textwrap
from select import select
from shlex import quote
from subprocess import PIPE, STDOUT, Popen

from slideception import bash, display_slides, flair, format_slide, ipython, slide, wait


@slide
def efficiency():
    """How to run the efficiency slides

    Follow these instructions to give a great presentation!

    * Make sure the terminal is at least 70 columns wide.
    * Type **Ctrl+D** to get a shell.
    * Type **Ctrl+L** to clear the screen (sneaky!)
    * Run the previous command from history.
    """
    bash(history=["./efficiency_slides"])


@slide
def end():
    """But wait... there’s more??

    ## Nested slide decks?

    * Since slides can run arbitrary code...
    """
    code = inspect.getsource(efficiency)
    print(format_slide(f"```python3\n{code}\n```"), end="")
    wait(more=False)


@slide
def zen():
    """Closing remarks

    I hope you learned something (or were at least somewhat entertained)!

    * [https://github.com/kalgynirae](/)
    """

    def readpty(fd):
        data = os.read(fd, 1024)
        return data.replace(
            b"Namespaces",
            b"\x1b[33;9mNamespaces\x1b[0m\x1b[32;4mNested slide decks\x1b[0m",
        ).replace(b"Python, by", b"Python, \x1b[3mmostly\x1b[23m by")

    os.chdir("zen")
    pty.spawn(["bash", "-i"], readpty)


with flair():
    display_slides()
